"""
Synthetic sample data generator.

    python -m nifty_algo.data.sample

Writes `data/sample_nifty_5m.csv`: several sessions of 5-minute bars with a
deliberate mix of day types - a range day, a trend day, a gap day, and a
compression-then-expansion day - so every strategy in the library has
something to fire on and the UI has something to draw.

THIS IS FABRICATED DATA. It exists so the pipeline can be exercised without a
broker account. A strategy "working" on this file means the code path runs,
nothing more - the price series was generated by a random walk that knows
nothing about how Nifty actually behaves. Backtest numbers from this file are
meaningless. Replace it with real Fyers or Dhan history before drawing any
conclusion about edge.
"""
from __future__ import annotations
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

BARS_PER_SESSION = 75          # 09:15 -> 15:30 at 5-minute bars
SESSION_START = (9, 15)


def _session_bars(day: datetime, open_price: float, drift: float,
                  vol: float, rng: np.random.Generator,
                  compress_from: int | None = None) -> pd.DataFrame:
    """One session of bars as a geometric-ish random walk with a drift term."""
    rows = []
    price = open_price
    start = day.replace(hour=SESSION_START[0], minute=SESSION_START[1],
                        second=0, microsecond=0)

    for i in range(BARS_PER_SESSION):
        # A compression window narrows the bars, then releases into a burst -
        # this is what gives the squeeze strategy something to detect.
        local_vol = vol
        if compress_from is not None:
            if compress_from <= i < compress_from + 8:
                local_vol = vol * 0.25
            elif compress_from + 8 <= i < compress_from + 14:
                local_vol = vol * 2.5

        step = rng.normal(drift, local_vol)
        o = price
        c = price + step
        wick = abs(rng.normal(0, local_vol * 0.6))
        h = max(o, c) + wick
        l = min(o, c) - wick

        base_vol = 90_000
        surge = 2.2 if (compress_from is not None
                        and compress_from + 8 <= i < compress_from + 14) else 1.0
        volume = int(abs(rng.normal(base_vol, base_vol * 0.35)) * surge) + 1_000

        rows.append({
            "timestamp": start + timedelta(minutes=5 * i),
            "open": round(o, 2), "high": round(h, 2),
            "low": round(l, 2), "close": round(c, 2),
            "volume": volume,
        })
        price = c

    return pd.DataFrame(rows)


def generate(seed: int = 7, start_price: float = 26_000.0,
             sessions: int = 8) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    frames: list[pd.DataFrame] = []
    price = start_price

    # Cycle deliberately through day archetypes rather than leaving it to
    # chance, so the sample always exercises every strategy.
    #        (drift, vol,  gap_pts, compress_at)
    plan = [
        (0.0,  6.0,   0.0,  None),   # range day
        (2.2,  7.0,   0.0,  None),   # trend up day
        (0.2,  5.0,  55.0,  None),   # gap up day
        (0.0,  5.5,   0.0,    30),   # squeeze then expansion
        (-2.0, 7.5,   0.0,  None),   # trend down day
        (0.1,  5.0, -48.0,  None),   # gap down day
        (0.0,  6.5,   0.0,    22),   # squeeze then expansion
        (1.2,  8.0,   0.0,  None),   # volatile trend day
    ]

    day = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
    day -= timedelta(days=sessions + 4)

    made = 0
    while made < sessions:
        day += timedelta(days=1)
        if day.weekday() >= 5:                      # skip weekends
            continue
        drift, vol, gap, compress_at = plan[made % len(plan)]
        price += gap
        frame = _session_bars(day, price, drift, vol, rng, compress_at)
        frames.append(frame)
        price = float(frame["close"].iloc[-1])
        made += 1

    return pd.concat(frames, ignore_index=True)


def main() -> None:
    out = Path("data/sample_nifty_5m.csv")
    out.parent.mkdir(parents=True, exist_ok=True)
    df = generate()
    df.to_csv(out, index=False)
    print(f"Wrote {len(df):,} bars across "
          f"{df['timestamp'].dt.date.nunique()} sessions -> {out}")
    print(f"Range: {df['low'].min():,.1f} - {df['high'].max():,.1f}")
    print("\nThis is FABRICATED data for exercising the pipeline.")
    print("Backtest results from it mean nothing. Replace with real history.")


if __name__ == "__main__":
    main()
